name: Upgrade dependencies

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_1
    - cron: '0 8 * * 1'
  workflow_dispatch:

concurrency:
  group: upgrade-dependencies
  cancel-in-progress: true

jobs:
  upgrade-dependencies:
    uses: nhoizey/upgrade-dependencies/.github/workflows/upgrade-dependencies.yml@dc4e57d9bc739655aa6c295ce86863a74e4a0dd8 # main as of 2026-09-19
    permissions:
      contents: read
    secrets:
      PAT: ${{ secrets.PAT }}
