# Reasonably configurable lists of domains for filters
DOMAIN_CONFIG = {
    "video": {
        "youtube.com",
        "youtu.be",
        "vimeo.com",
        "twitch.tv",
        "dailymotion.com",
        "tiktok.com",
    },
    "picture": {
        "flickr.com",
        "imgur.com",
        "instagram.com",
        "500px.com",
        "deviantart.com",
    },
    "tech": {
        "github.com",
        "gitlab.com",
        "pypi.org",
        "npmjs.com",
        "stackoverflow.com",
        "huggingface.co",
    },
    "news": {
        "pbs.org",
        "nytimes.com",
        "theguardian.com",
        "bbc.com",
        "bbc.co.uk",
        "cnn.com",
        "washingtonpost.com",
        "reuters.com",
        "aljazeera.com",
        "npr.org",
        "arstechnica.com",
        "economist.com",
        "wsj.com",
        "cnbc.com",
        "france24.com",
        "nbcnews.com",
        "politico.com",
        "statnews.com",
        "nbcnewyork.com",
        "news.sky.com",
    },
}